### ISSUE TITLE
FDA code for Table 14-3.01 & Table 14-3.02 (potential round off issue)

### ISSUE THREAD

**Issue by hyescho** [RConsortium/submissions-pilot1-to-fda#10]
**FDA Code for Table 14-3.01**
`
#--------------------------- Loading data
library(SASxport)
adadas_address <- # Put the directory of adadas.xpt here
adadas <- read.xport(adadas_address) 

#--------------------------- Filtering data
library(tidyverse)
adadas_sub <- adadas %>% 
  filter(STUDYID == 'CDISCPILOT01' & EFFFL == 'Y' & ITTFL == 'Y' & ANL01FL == 'Y' & PARAMCD == 'ACTOT') 

#--------------------------- Baseline
baseline <- adadas_sub %>% 
  filter(AVISIT == 'Baseline') %>%
  group_by(TRTP) %>%
  dplyr::summarise(n = n(), 
                   mean =  formatC(mean(AVAL), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(AVAL), digits = 2, format = "f", flag = "#"), 
                   median = formatC(median(AVAL), digits = 1, format = "f", flag = "#"),
                   min = round(min(AVAL)),
                   max = round(max(AVAL))) %>%
  mutate("Mean (SD)" = paste0(mean, " (", sd, ")"), 
         "Median (Range)" = paste0(median, " (", min, ";", max, ")")) %>%
  select(TRTP, n, "Mean (SD)", "Median (Range)")
baseline <- baseline %>%
  gather("Parameter", "value", 2:ncol(baseline), factor_key = TRUE) %>%
  spread(TRTP, value)

#--------------------------- Week 24
week24 <- adadas_sub %>% 
  filter(AVISIT == 'Week 24') %>%
  group_by(TRTP) %>%
  dplyr::summarise(n = n(), 
                   mean =  formatC(mean(AVAL), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(AVAL), digits = 2, format = "f", flag = "#"), 
                   median = formatC(median(AVAL), digits = 1, format = "f", flag = "#"),
                   min = round(min(AVAL)),
                   max = round(max(AVAL))) %>%
  mutate("Mean (SD)" = paste0(mean, " (", sd, ")"), 
         "Median (Range)" = paste0(median, " (", min, ";", max, ")")) %>%
  select(TRTP, n, "Mean (SD)", "Median (Range)")
week24 <- week24 %>%
  gather("Parameter", "value", 2:ncol(baseline), factor_key = TRUE) %>%
  spread(TRTP, value)

#--------------------------- Change from baseline
CHG_week24 <- adadas_sub %>% 
  filter(AVISIT == 'Week 24') %>%
  group_by(TRTP) %>%
  dplyr::summarise(n = n(), 
                   mean =  formatC(mean(CHG), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(CHG), digits = 2, format = "f", flag = "#"), 
                   median = formatC(median(CHG), digits = 1, format = "f", flag = "#"),
                   min = round(min(CHG)),
                   max = round(max(CHG))) %>%
  mutate("Mean (SD)" = paste0(mean, " (", sd, ")"), 
         "Median (Range)" = paste0(median, " (", min, ";", max, ")")) %>%
  select(TRTP, n, "Mean (SD)", "Median (Range)")
CHG_week24 <- CHG_week24 %>%
  gather("Parameter", "value", 2:ncol(baseline), factor_key = TRUE) %>%
  spread(TRTP, value)

#--------------- ANCOVA model
library(car)
library(lsmeans)
subset_week24 <- adadas_sub %>% 
  filter(AVISIT == 'Week 24')

#--------------- p-value (Dose Response)
lm_model_cont_trt <- lm(CHG ~ TRTPN + as.factor(SITEGR1) + BASE, data = subset_week24)
pvalue_dose_response <- round(summary(lm_model_cont_trt)$coefficients["TRTPN",4], 3)

#--------------------------- Xan - Placebo
lm_model <- lm(CHG ~ TRTP + as.factor(SITEGR1) + BASE, data = subset_week24)
lsm_model <- lsmeans(lm_model, "TRTP")
pairwise_lsm_rev_model <- pairs(lsm_model, reverse = TRUE)

#Output of summary(pairwise_lsm_rev_model)
#contrast                                   estimate    SE  df t.ratio p.value
#Xanomeline High Dose - Placebo               -1.006 0.841 220  -1.197  0.4563
#Xanomeline Low Dose - Placebo                -0.467 0.818 220  -0.571  0.8359
#Xanomeline Low Dose - Xanomeline High Dose    0.539 0.836 220   0.645  0.7954

pairwise_lsm_rev <- summary(pairwise_lsm_rev_model) %>%
  as.data.frame() %>%
  mutate(diff_se = paste0(formatC(estimate, digits = 1, format = "f", flag = "#"), " (", formatC(SE, digits = 2, format = "f", flag = "#"), ")"),
         conf = paste0("(", formatC(estimate - 1.96 * SE, digits = 1, format = "f", flag = "#"), ";", formatC(estimate + 1.96 *SE, digits = 1, format = "f", flag = "#"), ")"),
         p.value = formatC(2 * pt(estimate/SE, df), digits = 3, format = "f", flag = "#")) %>%
  select(contrast, diff_se, conf, p.value)

#Output of pairwise_lsm_rev
#contrast     diff_se       conf p.value
#1             Xanomeline High Dose - Placebo -1.0 (0.84) (-2.7;0.6)   0.233
#2              Xanomeline Low Dose - Placebo -0.5 (0.82) (-2.1;1.1)   0.569
#3 Xanomeline Low Dose - Xanomeline High Dose  0.5 (0.84) (-1.1;2.2)   1.480

#--------------------------- Xan High - Xan Low
pairwise_lsm_model <- pairs(lsm_model)

pairwise_lsm <- summary(pairwise_lsm_model) %>%
  as.data.frame() %>%
  mutate(diff_se = paste0(formatC(estimate, digits = 1, format = "f", flag = "#"), " (", formatC(SE, digits = 2, format = "f", flag = "#"), ")"),
         conf = paste0("(", formatC(estimate - 1.96 * SE, digits = 1, format = "f", flag = "#"), ";", formatC(estimate + 1.96 *SE, digits = 1, format = "f", flag = "#"), ")"),
         p.value = formatC(2 * pt(estimate/SE, df), digits = 3, format = "f", flag = "#")) %>%
  select(contrast, diff_se, conf, p.value)

#--------------------------- Generating table
table <- rbind(baseline, week24, CHG_week24)
table$Parameter <- as.character(table$Parameter)

insertRow <- function(existingDF, newrow, r) {
  existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
  existingDF[r,] <- newrow
  existingDF
}
table <- insertRow(table, "Baseline", 1)
table <- insertRow(table, "Week 24", 5)
table <- insertRow(table, "Change from Baseline", 9)

table[c(1,5,9), 2:ncol(table)] <- ""

table <- rbind(table, c("p-value (Dose Response) [1][2]", "", pvalue_dose_response, ""))
table <- rbind(table, "")
table <- rbind(table, 
               c("p-value (Xan - Placebo) [1][3]", "", pairwise_lsm_rev$p.value[1], pairwise_lsm_rev$p.value[2]),
               c("   Diff of LS Means (SE)", "", pairwise_lsm_rev$diff_se[1], pairwise_lsm_rev$diff_se[2]),
               c("   95% CI", "", pairwise_lsm_rev$conf[1], pairwise_lsm_rev$conf[2]))
table <- rbind(table, "")
table <- rbind(table, 
               c("p-value (Xan High - Xan Low) [1][3]", "", pairwise_lsm$p.value[3], ""),
               c("   Diff of LS Means (SE)", "", pairwise_lsm$diff_se[3], ""),
               c("   95% CI", "", pairwise_lsm$conf[3], ""))

library(r2rtf)
rtf_table <- table %>%
  rtf_page(orientation = "landscape",
           margin = c(.25,.25,.25,.25,.25,.25)) %>%
  rtf_page_header(text_space = 1, text_font = 3) %>%
  rtf_title("Table 14-3.01 Primary Endpoint Analysis: ADAS Cog (11) - Change from Baseline to Week 24 - LOCF", 
            text_justification = "l",
            text_font = 3,
            text_font_size = 10, 
            text_format = "b") %>%
  rtf_colheader(paste0(colnames(table), collapse = " | "),
                text_convert = FALSE,
                col_rel_width = c(1.3, rep(1, ncol(table)-1))) %>%
  rtf_body(col_rel_width = c(1.3, rep(1, ncol(table)-1)), 
           text_justification = c("l", rep("c", ncol(table)-1)), 
           text_font = 3,
           text_font_size = 10, 
           border_right = NULL, 
           border_left = NULL) %>%
  rtf_footnote(footnote = paste("Source: adadas.xpt; Software:", R.Version()$version.string,"\n[1] Based on Analysis of covariance (ANCOVA) model with treatment and site group as factors and baseline value as a covariate. \n[2] Test for a non-zero coefficient for treatment (dose) as a continuous variable \n[3] Pairwise comparison with treatment as a categorical variable: p-values without adjustment for multiple comparisons.\n", 
                                Sys.time()), 
               text_font = 3,
               text_font_size = 8,
               text_justification = "l", 
               border_left = NULL,
               border_right = NULL,
               border_top = NULL,
               border_bottom = NULL) %>%
  rtf_encode() %>%
  write_rtf(paste(getwd(),"/", sep = "", "Table14-3.01.rtf"))
`

**FDA Code for Table 14-3.02**
`
#--------------------------- Loading data
library(SASxport)
adlbc_address <- # Put the directory of adlbc.xpt here
adlbc <- read.xport(adlbc_address) 

#--------------------------- Filtering data
library(tidyverse)
adlbc_sub <- adlbc %>% 
  filter(STUDYID == 'CDISCPILOT01' & TRTPN %in% c(0, 81) & PARAMCD == 'GLUC' & !is.na(AVISITN))

#------------------------- Baseline
baseline <- adlbc_sub %>% 
  filter(AVISIT == 'Week 20') %>%
  group_by(TRTP) %>%
  dplyr::summarise(N = n(), 
                   mean =  formatC(mean(BASE), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(BASE), digits = 2, format = "f", flag = "#")) %>%
  mutate("Mean(SD)" = paste0(mean, " (", sd, ")")) %>% 
  select(TRTP, N, "Mean(SD)")

#------------------------- Week 20
week24 <- adlbc_sub %>% 
  filter(AVISIT == 'Week 20') %>%
  group_by(TRTP) %>%
  dplyr::summarise(N = n(), 
                   mean =  formatC(mean(AVAL), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(AVAL), digits = 2, format = "f", flag = "#")) %>%
  mutate("Mean(SD)" = paste0(mean, " (", sd, ")")) %>% 
  select(TRTP, N, "Mean(SD)")

#------------------------- Change from Baseline
CHG_week24 <- adlbc_sub %>% 
  filter(AVISIT == 'Week 20') %>%
  group_by(TRTP) %>%
  dplyr::summarise(N = n(), 
                   mean =  formatC(mean(CHG), digits = 1, format = "f", flag = "#"), 
                   sd = formatC(sd(CHG), digits = 2, format = "f", flag = "#")) %>%
  mutate("Mean(SD)" = paste0(mean, " (", sd, ")")) %>% 
  select(TRTP, N, "Mean(SD)")

subset_data_CHG <- adlbc_sub %>% 
  filter(AVISIT == 'Week 20')
lm_model <- lm(CHG ~ BASE + TRTP, data = subset_data_CHG)
lsm_model <- lsmeans(lm_model, "TRTP")
pairwise_lsm_model <- pairs(lsm_model, reverse = TRUE)

lsm <- summary(lsm_model) %>%
  as.data.frame() %>%
  mutate("LS Mean (95% CI)" = paste0(formatC(lsmean, digits = 2, format = "f", flag = "#"), " (",
                                     formatC(lower.CL, digits = 2, format = "f", flag = "#"), ", ", 
                                     formatC(upper.CL, digits = 2, format = "f", flag = "#"), ")")) %>%
  select(TRTP, "LS Mean (95% CI)")

#------------------------- Pairwise Comparison
table2 <- summary(pairwise_lsm_model) %>%
  as.data.frame() %>%
  mutate(mean = paste0(formatC(estimate, digits = 2, format = "f", flag = "#"), " (", 
                       formatC(estimate - 1.96 * SE, digits = 2, format = "f", flag = "#"), ",", 
                       formatC(estimate + 1.96 *SE, digits = 2, format = "f", flag = "#"), ")"), 
         P = formatC(p.value, digits = 3, format = "f", flag = "#")) %>%
  select(contrast, mean, P)

#------------------------- Root Mean Squared Error of Change
rmse_value <- sqrt(mean(lm_model$residuals^2))  # rmse_value = 1.302627
table3 <- as.data.frame(paste0("Root Mean Squared Error of Change = ", formatC(rmse_value,digits = 2, format = "f", flag = "#")))
colnames(table3) <- "rmse"

#------------------------- Generating table
table1 <- cbind(baseline, week24[,-1], CHG_week24[,-1], lsm[,"LS Mean (95% CI)"])
table1 <- rbind(table1[2,], table1[1,])
colnames(table1) <- c("Trt", "N1", "Mean1", "N2", "Mean2", "N3", "Mean3", "CI") 

tb1 <- table1 %>%
  rtf_title(title = "ANCOVA of Change from Baseline at Week 20" #,
            #subtitle = c("LOCF",
            #             "ITT Population")) 
            ) %>%
  rtf_colheader(colheader = " | Baseline{^a} | Week 20 | Change from Baseline",
                col_rel_width = c(3, 4, 4, 9)) %>%
  rtf_colheader(colheader = "Treatment | N | Mean (SD) | N | Mean (SD) | N | Mean (SD) | LS Mean (95% CI){^b}", 
                col_rel_width = c(3,1,3,1,3,1,3,5)) %>%
  rtf_body(col_rel_width = c(3,1,3,1,3,1,3,5),
           text_justification = c("l",rep("c",7))) %>%
  rtf_footnote(footnote = paste0("{^a} Table is based on participants who have observable data at Baseline and Week 20. \n{^b} Based on an Analysis of covariance (ANCOVA) model with treatment and baseline value as a covariate. \nCI = Confidence Interval, LS = Least Squares, SD = Standard Deviation\nSource: adlbc.xpt; Software:", R.Version()$version.string,"\n",Sys.time())) 

tb2 <- table2 %>%
  rtf_colheader(colheader = "Pairwise Comparison | Difference in LS Mean(95% CI){^b} | p-Value",
                text_justification = c("l","c","c"), 
                col_rel_width = c(8,7,5)) %>%
  rtf_body(col_rel_width = c(8,7,5),
           text_justification = c("l","c","c"),
           last_row = FALSE)
tb3 <- table3 %>%
  rtf_body(as_colheader = FALSE,
           text_justification = "l")

tbl <- list(tb1, tb2, tb3)
tbl %>%
  rtf_encode() %>%
  write_rtf(paste(getwd(),"/", sep = "", "Table14-3.02.rtf"))
`

**Comment by jtisack** [comment]
Regarding the discrepancy in Table 14-3.01, the FDA code uses an approximation to compute the confidence intervals. The issue appears to be fixed by replacing the approximate value 1.96 with the precise quantile qt(.975, df).

Original code:

```R
pairwise_lsm_rev <- summary(pairwise_lsm_rev_model) %>%
  as.data.frame() %>%
  mutate(diff_se = paste0(formatC(estimate, digits = 1, format = "f", flag = "#"), " (", formatC(SE, digits = 2, format = "f", flag = "#"), ")"),
         conf = paste0("(", formatC(estimate - 1.96 * SE, digits = 1, format = "f", flag = "#"), ";", formatC(estimate + 1.96 *SE, digits = 1, format = "f", flag = "#"), ")"),
         p.value = formatC(2 * pt(estimate/SE, df), digits = 3, format = "f", flag = "#")) %>%
  select(contrast, diff_se, conf, p.value)
```

Modified:

```R
pairwise_lsm_rev <- summary(pairwise_lsm_rev_model) %>%
  as.data.frame() %>%
  mutate(diff_se = paste0(formatC(estimate, digits = 1, format = "f", flag = "#"), " (", formatC(SE, digits = 2, format = "f", flag = "#"), ")"),
         conf = paste0("(", formatC(estimate - qt(.975, df) * SE, digits = 1, format = "f", flag = "#"), ";", formatC(estimate + qt(.975, df) *SE, digits = 1, format = "f", flag = "#"), ")"),
         p.value = formatC(2 * pt(estimate/SE, df), digits = 3, format = "f", flag = "#")) %>%
  select(contrast, diff_se, conf, p.value)
```

**Comment by jtisack** [comment]
For the discrepancy in Table 14-3.02, it has already been addressed. The submission package calculation for the RMSE was different than the FDA calculation, but was changed to match the FDA method here:

https://github.com/RConsortium/submissions-pilot1/commit/bff8fe0d6396d29fa69a9f74180639c3368a2f20#diff-c14d382c6edfd3e572e2eab1a9b1de7e3762894cddf86672011a7570a7959103L101

The reason for the difference is that the sd() function uses the Bessel correction (i.e. n - 1 in the denominator).

**Comment by elong0527** [comment]
Thank you all. In the response letter, we explained the issue as below. 

> The rounding issue in Table 14-3.02 has been addressed after updating the approach to calculate RMSE. The rounding issue in Table 14-3.01 is because of ways to calculate the 97.5% quantile of the standard normal distribution. We keep our existing code instead of using 1.96.

**Comment by hyescho** [comment]
Thank you for addressing and explaining the discrepancies. 
I would like to confirm one more thing for table 14-3.02. I noticed that 1.96, not the 97.5% quantile of the standard normal distribution, was used to calculate the 95% CI of difference in LS means in table 14-3.02, as you can see the code below. If we use the 97.5% quantile instead of 1.96, the lower and upper limits change. We may want to choose one way to calculate the 95% CI to keep consistency. 

[vignettes/tlf-efficacy.Rmd](https://github.com/RConsortium/submissions-pilot1/blob/main/vignettes/tlf-efficacy.Rmd)
```
## Treatment Comparison
apr0ancova2 <- t2 %>%
  mutate(
    lower = estimate - 1.96 * SE,
    upper = estimate + 1.96 * SE
  ) %>%
  mutate(
    comp = "Xanomeline High Dose vs. Placebo",
    mean = pilot1wrappers::fmt_ci(estimate, lower, upper),
    p = pilot1wrappers::fmt_pval(p.value)
  ) %>%
  select(comp:p)

```
