### ISSUE TITLE
Feedback from reviewers

### ISSUE THREAD

**Issue by elong0527** [RConsortium/submissions-pilot1-to-fda#3]
1. Create a package dependency chart 
2. Each R file shall be able to run independently. 
3. Enhance the pkglite instruction in ADRG (install package without write permission)
4. More clarification in program header to help reviewer identify potential issues. (e.g. check write permission)

**Comment by elong0527** [comment]
@lengning , could you provide a link to a ADRG document that I can edit? Thanks!

**Comment by elong0527** [comment]
A PR is created to update source code. 

We will need to update submission program after the PR below is merged.

https://github.com/RConsortium/submissions-pilot1/pull/14

**Comment by lengning** [comment]
ADRG working doc: https://drive.google.com/drive/u/1/folders/1g_7onRSO__Voalx7xjJWFgDXO7DVw8H_

(archived the Nov submission materials under folder pilot 1 submission1)

**Comment by elong0527** [comment]
The ADRG is updated.

**Comment by elong0527** [comment]
Based on FDA response letter https://github.com/RConsortium/submissions-wg/blob/main/Documents/Summary_R_Pilot_Submission.pdf

We need to address comments below:

- [x] column header are switched in Table 14-3.0.1  
- [x] follow format suggested by reviewer in Table 14-3.02

For rounding issue, my guess is due to different environment:

- OS: we run it on RStudio Cloud that is a Linux system. 
- R version. (ADRG indicated R4.1.0, yet FDA response letter uses R4.1.1)

**Comment by elong0527** [comment]
All TLF related comments has been addressed. Action item for ADRG

- [x] update R version to R4.1.2
- [ ] update data source per FDA review comments. 

"In the Analysis Data Reviewer’s Guide, adrg, the analysis dataset is incorrectly specified
(ADLBC, not ADLB, in section 7.03 page 12). "

**Comment by michaelmayer2** [comment]
In reference to https://github.com/RConsortium/submissions-pilot1-to-fda/issues/3#issuecomment-1005983862 I would suggest to compare the output of `sessionInfo() ` My suspicion is that the FDA R installation uses a different LAPACK/BLAS implementation than rstudio cloud. 

In Rstudio cloud I see 

```bash
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2   
```

where the most interesting lines are the ones starting with LAPACK and BLAS

Additionally we also should compare underlying processor instruction sets (i.e. `cat /proc/cpuinfo` if on a Linux system)

Both LAPACK/BLAS as well as processor instruction set can lead to rounding errors independent of the R version.

**Comment by elong0527** [comment]
The submission package has been updated to reflect the change.
