### ISSUE TITLE
Was any validation done on the internal package? If yes, how was it documented and communicated?

### ISSUE THREAD

**Issue by fh-nphillips** [RConsortium/submissions-pilot1-to-fda#6]
First, I want to thank the team so much for conducting and sharing this very impressive work! We are following it very closely and hope to use it as a model for future regulatory submissions using R.

One question has come up regarding validation: As part of this pilot project, did the authors provide documentation of how the internal package was validated / reviewed? If yes, can you provide that documentation and any feedback given by the FDA? If not, was it because validation was out of scope for this pilot project? Any thoughts on how it would be provided if this was indeed a 'real' submission?

Looking forward to hearing your thoughts!

**Comment by elong0527** [comment]
The validation is out of scope for this project. 

You may refer other work related to process to validate internal R packages. 

For example: 
https://www.pharmasug.org/proceedings/2021/SI/PharmaSUG-2021-SI-084.pdf

**Comment by fh-nphillips** [comment]
Thank you @elong0527 !
